import Link from "next/link"

import { siteConfig } from "@/config/site"
import { Printer, columns } from "./columns"
import { DataTable } from "./data-table"
async function getData(): Promise<Printer[]> {
  // Fetch data from your API here.
  return [
    {
      id: 1,
      printer_name: "Printer A",
      printer_type: "Prusa",
      ip: "192.168.1.10",
      api_key: "abc123",
      total_filament_used: 200,
      total_time_printed: 5000,
      failed_prints: 5,
      completed_prints: 100,
      days_on_time: 30,
      location: "Office A",
    },
    {
      id: 2,
      printer_name: "Printer B",
      printer_type: "Prusa",
      ip: "192.168.1.11",
      api_key: "xyz789",
      total_filament_used: 100,
      total_time_printed: 3000,
      failed_prints: 2,
      completed_prints: 50,
      days_on_time: 20,
      location: "Office B",
    },
    {
      id: 1,
      printer_name: "Printer A",
      printer_type: "Prusa",
      ip: "192.168.1.10",
      api_key: "abc123",
      total_filament_used: 200,
      total_time_printed: 5000,
      failed_prints: 5,
      completed_prints: 100,
      days_on_time: 30,
      location: "Office A",
    },
    {
      id: 2,
      printer_name: "Printer B",
      printer_type: "Prusa",
      ip: "192.168.1.11",
      api_key: "xyz789",
      total_filament_used: 100,
      total_time_printed: 3000,
      failed_prints: 2,
      completed_prints: 50,
      days_on_time: 20,
      location: "Office B",
    },
    {
      id: 1,
      printer_name: "Printer A",
      printer_type: "Prusa",
      ip: "192.168.1.10",
      api_key: "abc123",
      total_filament_used: 200,
      total_time_printed: 5000,
      failed_prints: 5,
      completed_prints: 100,
      days_on_time: 30,
      location: "Office A",
    },
    {
      id: 2,
      printer_name: "Printer B",
      printer_type: "Prusa",
      ip: "192.168.1.11",
      api_key: "xyz789",
      total_filament_used: 100,
      total_time_printed: 3000,
      failed_prints: 2,
      completed_prints: 50,
      days_on_time: 20,
      location: "Office B",
    },
    {
      id: 1,
      printer_name: "Printer A",
      printer_type: "Prusa",
      ip: "192.168.1.10",
      api_key: "abc123",
      total_filament_used: 200,
      total_time_printed: 5000,
      failed_prints: 5,
      completed_prints: 100,
      days_on_time: 30,
      location: "Office A",
    },
    {
      id: 2,
      printer_name: "Printer B",
      printer_type: "Prusa",
      ip: "192.168.1.11",
      api_key: "xyz789",
      total_filament_used: 100,
      total_time_printed: 3000,
      failed_prints: 2,
      completed_prints: 50,
      days_on_time: 20,
      location: "Office B",
    },
    {
      id: 1,
      printer_name: "Printer A",
      printer_type: "Prusa",
      ip: "192.168.1.10",
      api_key: "abc123",
      total_filament_used: 200,
      total_time_printed: 5000,
      failed_prints: 5,
      completed_prints: 100,
      days_on_time: 30,
      location: "Office A",
    },
    {
      id: 2,
      printer_name: "Printer B",
      printer_type: "Prusa",
      ip: "192.168.1.11",
      api_key: "xyz789",
      total_filament_used: 100,
      total_time_printed: 3000,
      failed_prints: 2,
      completed_prints: 50,
      days_on_time: 20,
      location: "Office B",
    },
    {
      id: 1,
      printer_name: "Printer A",
      printer_type: "Prusa",
      ip: "192.168.1.10",
      api_key: "abc123",
      total_filament_used: 200,
      total_time_printed: 5000,
      failed_prints: 5,
      completed_prints: 100,
      days_on_time: 30,
      location: "Office A",
    },
    {
      id: 2,
      printer_name: "Printer B",
      printer_type: "Prusa",
      ip: "192.168.1.11",
      api_key: "xyz789",
      total_filament_used: 100,
      total_time_printed: 3000,
      failed_prints: 2,
      completed_prints: 50,
      days_on_time: 20,
      location: "Office B",
    },
    {
      id: 1,
      printer_name: "Printer A",
      printer_type: "Prusa",
      ip: "192.168.1.10",
      api_key: "abc123",
      total_filament_used: 200,
      total_time_printed: 5000,
      failed_prints: 5,
      completed_prints: 100,
      days_on_time: 30,
      location: "Office A",
    },
    {
      id: 2,
      printer_name: "Printer B",
      printer_type: "Prusa",
      ip: "192.168.1.11",
      api_key: "xyz789",
      total_filament_used: 100,
      total_time_printed: 3000,
      failed_prints: 2,
      completed_prints: 50,
      days_on_time: 20,
      location: "Office B",
    },
    {
      id: 1,
      printer_name: "Printer A",
      printer_type: "Prusa",
      ip: "192.168.1.10",
      api_key: "abc123",
      total_filament_used: 200,
      total_time_printed: 5000,
      failed_prints: 5,
      completed_prints: 100,
      days_on_time: 30,
      location: "Office A",
    },
    {
      id: 2,
      printer_name: "Printer B",
      printer_type: "Prusa",
      ip: "192.168.1.11",
      api_key: "xyz789",
      total_filament_used: 100,
      total_time_printed: 3000,
      failed_prints: 2,
      completed_prints: 50,
      days_on_time: 20,
      location: "Office B",
    },
    {
      id: 1,
      printer_name: "Printer A",
      printer_type: "Prusa",
      ip: "192.168.1.10",
      api_key: "abc123",
      total_filament_used: 200,
      total_time_printed: 5000,
      failed_prints: 5,
      completed_prints: 100,
      days_on_time: 30,
      location: "Office A",
    },
    {
      id: 2,
      printer_name: "Printer B",
      printer_type: "Prusa",
      ip: "192.168.1.11",
      api_key: "xyz789",
      total_filament_used: 100,
      total_time_printed: 3000,
      failed_prints: 2,
      completed_prints: 50,
      days_on_time: 20,
      location: "Office B",
    },
    {
      id: 1,
      printer_name: "Printer A",
      printer_type: "Prusa",
      ip: "192.168.1.10",
      api_key: "abc123",
      total_filament_used: 200,
      total_time_printed: 5000,
      failed_prints: 5,
      completed_prints: 100,
      days_on_time: 30,
      location: "Office A",
    },
    {
      id: 2,
      printer_name: "Printer B",
      printer_type: "Prusa",
      ip: "192.168.1.11",
      api_key: "xyz789",
      total_filament_used: 100,
      total_time_printed: 3000,
      failed_prints: 2,
      completed_prints: 50,
      days_on_time: 20,
      location: "Office B",
    },
    {
      id: 1,
      printer_name: "Printer A",
      printer_type: "Prusa",
      ip: "192.168.1.10",
      api_key: "abc123",
      total_filament_used: 200,
      total_time_printed: 5000,
      failed_prints: 5,
      completed_prints: 100,
      days_on_time: 30,
      location: "Office A",
    },
    {
      id: 2,
      printer_name: "Printer B",
      printer_type: "Prusa",
      ip: "192.168.1.11",
      api_key: "xyz789",
      total_filament_used: 100,
      total_time_printed: 3000,
      failed_prints: 2,
      completed_prints: 50,
      days_on_time: 20,
      location: "Office B",
    },
    {
      id: 1,
      printer_name: "Printer C",
      printer_type: "Prusa",
      ip: "192.168.1.10",
      api_key: "abc123",
      total_filament_used: 200,
      total_time_printed: 5000,
      failed_prints: 5,
      completed_prints: 100,
      days_on_time: 30,
      location: "Office A",
    },
    {
      id: 2,
      printer_name: "Printer B",
      printer_type: "Prusa",
      ip: "192.168.1.11",
      api_key: "xyz789",
      total_filament_used: 100,
      total_time_printed: 3000,
      failed_prints: 2,
      completed_prints: 50,
      days_on_time: 20,
      location: "Office B",
    },

    // add more objects here as needed
  ];
}

export default async function PrintersPage() {
  const data = await getData()

  return (
    <section className="container grid items-center gap-6 pb-8 pt-6 md:py-10">
      <div className="flex max-w-[980px] flex-col items-start gap-2">
        <h1 className="text-3xl font-extrabold leading-tight tracking-tighter sm:text-3xl md:text-5xl lg:text-6xl">
          Printers
        </h1>
      </div>
      <div className="flex gap-4">
        <DataTable columns={columns} data={data} />
      </div>
    </section>
  )
}
